### ISSUE TITLE
Allow PlatformIO Library Crawler to recognise "*"

### ISSUE THREAD

**Issue by gandy92** [platformio/platformio-api#2]
Currently, the PlatformIO Library Crawler does not recognise wildcards (`"*"`) for entries. This would be helpful however, in cases where a library is written for a specific framework (e.g. `arduino`) but is not limited to a specific platform. Here, two approaches seem possible:
- omit the `platform` entry in the manifest file: Currently, this entry is mandatory and can not be omitted
- allow statement `"platform": "*"` in the manifest file. The crawler could replace this with the list of platforms that work with the specified frameworks.

**Comment by ivankravets** [comment]
Resolved a few months before
