### ISSUE TITLE
Unicode characters in package.json

### ISSUE THREAD

**Issue by skore13** [platformio/platformio-api#21]
Tried to submit package with my name in it. Because it has accent it didn't work.

Relevant parts of email conversation:

> > Please replace non ascii chars in config:
> > "name": "Jakub Skořepa" -> "name": "Jakub Skorepa",
> 
>  I replaced ř with "\u0159" so it is valid JSON but still have my real name there.  Is this OK?

This is a bug in our API. Please open issue for that here https://github.com/platformio/platformio-api/issues

**Comment by ivankravets** [comment]
Fixed a few months ago
